apiVersion: v1
entries:
  helperChart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-24T20:20:40.015464+03:00"
    description: Storage class
    digest: cdf41a93ac4c32fb79e033de32a012c53b84044ecca739472d12872a107572c4
    maintainers:
    - name: Krasimir Koeff
      url: github.com/k0eff
    name: helperChart
    type: application
    urls:
    - https://github.com/k0eff/helmfile-home-lab/raw/main/helm/packages/helperChart-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-24T20:20:40.01525+03:00"
