helmDefaults:
  kubeContext: kubernetes-admin@cluster01-dev.local
missingFileHandler: Error


repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: k0eff-home-lab-charts
    url: https://github.com/k0eff/helmfile-home-lab/raw/main/helm/packages/
  - name: metallb
    url: https://metallb.github.io/metallb/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: nextcloud
    url: https://nextcloud.github.io/helm/
---

environments: # envs need to be in a different part of the yaml, to avoid the chicken&egg problem
  cluster01-dev:
    values:
      - ../../values/common/shared.yaml
      - ../../values/cluster01-dev/cluster01-dev-vals.yaml
      - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
  default:
    values:

---

releases:
  - name: storage-class-default
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: "helperchart.storageClass.fstype"
        value: xfs # https://www.phoronix.com/review/linux-58-filesystems/4
      - name: "helperchart.storageClass.storagePolicyName"
        value: {{ .Environment.Name }}Policy
  - name: namespace-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.namespace.enabled"
        value: true
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
    createNamespace: false
  - name: organizr-main
    namespace: ns-homelab-main
    chart: k8s-at-home/organizr
    set:
    - name: persistence.config.size
      value: 500Mi
    values:
    - ../../templates/organizr/values.yaml.gotmpl
    installed: true
  - name: metallb-main
    namespace: {{.Values.helperchart.namespace.name}}
    chart: metallb/metallb
    installed: true
  - name: ipaddresspool-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.ipaddresspool.enabled"
        value: true
      - name: "helperchart.ipaddresspool.name"
        value: "internal"
      - name: "helperchart.ipaddresspool.namespace"
        value: {{.Values.helperchart.namespace.name}}
    values:
    - ../../values/{{ .Environment.Name }}/ipaddresspool-metallb.yaml
    needs: # as it uses a CRD - make sure to run the diff after installing the CRDs with the metallb release
    - ns-metallb/metallb-main
    installed: true
  - name: ingress-nginx-main
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    namespace: ns-homelab-main
    values:
    - ../../values/{{ .Environment.Name }}/ingress-nginx.yaml
  - name: nextcloud
    chart: nextcloud/nextcloud
    version: 4.2.1
    set:
      - name: image.repository
        value: k0eff/nextcloud-full
      - name: image.flavor
        value: fpm
      - name: image.tag
        value: full
      - name: ingress.className
        value: nginx
      - name: ingress.enabled
        value: true
      - name: nextcloud.host
        value: nextcloud.kube.home
      - name: nextcloud.username
        value: koeff
      - name: nextcloud.password
        value: "1231fds23123"
      - name: nginx.enabled
        value: true
      - name: peristence.enabled
        value: false
      - name: peristence.storageClass
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: nextcloud.extraInitContainers[0].name
        value: install-smbclient
      - name: nextcloud.extraInitContainers[0].image
        value: nextcloud:stable-fpm-alpine
      - name: nextcloud.extraInitContainers[0].command[0]
        value: sh
      - name: nextcloud.extraInitContainers[0].command[1]
        value: "-c"
      - name: nextcloud.extraInitContainers[0].command[2]
        value: "apk add --no-cache procps samba-client"
    needs:
    - ns-metallb/metallb-main
