helmDefaults:
  kubeContext: kubernetes-admin@cluster01-dev.local
missingFileHandler: Error


repositories:
  - name: k8s-at-home
    url: https://github.com/k0eff/k8s-at-home-charts/raw/master/koeff/packages
  - name: k0eff-home-lab-charts
    url: https://github.com/k0eff/helmfile-home-lab/raw/main/helm/packages/
  - name: metallb
    url: https://metallb.github.io/metallb/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: nextcloud
    url: https://nextcloud.github.io/helm/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: adfinis
    url: https://charts.adfinis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: cloudnativeapp
    url: https://cloudnativeapp.github.io/charts/curated/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: cetic
    url: https://cetic.github.io/helm-charts

---

environments: # envs need to be in a different part of the yaml, to avoid the chicken&egg problem
  cluster01-dev:
    values:
      - ../../values/common/shared.yaml
      - ../../values/cluster01-dev/cluster01-dev-vals.yaml
      - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
  default:
    values:

---

releases:
  - name: storage-class-default
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: "helperchart.storageClass.annotations.storageclass\\.kubernetes\\.io/is-default-class"
        value: true
      - name: "helperchart.storageClass.parameters.fstype"
        value: xfs # https://www.phoronix.com/review/linux-58-filesystems/4
      - name: "helperchart.storageClass.parameters.storagepolicyname"
        value: {{ .Environment.Name }}Policy
      - name: "helperchart.storageClass.allowVolumeExpansion"
        value: true
      - name: "helperchart.storageClass.provisioner"
        value: "csi.vsphere.vmware.com"
  - name: namespace-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.namespace.enabled"
        value: true
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
    createNamespace: false
  - name: organizr-main
    namespace: ns-homelab-main
    chart: k8s-at-home/organizr
    set:
    - name: persistence.config.size
      value: 500Mi
    values:
    - ../../templates/organizr/values.yaml.gotmpl
    installed: true
  - name: metallb-main
    namespace: {{.Values.helperchart.namespace.name}}
    chart: metallb/metallb
    version: "0.13.12"
    installed: true
  - name: ipaddresspool-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.ipaddresspool.enabled"
        value: true
      - name: "helperchart.ipaddresspool.name"
        value: "internal"
      - name: "helperchart.ipaddresspool.namespace"
        value: {{.Values.helperchart.namespace.name}}
    values:
    - ../../values/{{ .Environment.Name }}/ipaddresspool-metallb.yaml
    needs: # as it uses a CRD - make sure to run the diff after installing the CRDs with the metallb release
    - ns-metallb/metallb-main
    installed: true

  - name: ingress-nginx-main
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    namespace: ns-homelab-main
    values:
    - ../../values/{{ .Environment.Name }}/ingress-nginx.yaml
  - name: nextcloud
    chart: nextcloud/nextcloud
    version: 4.2.1
    installed: false
    set:
      - name: image.repository
        value: k0eff/nextcloud-full
      - name: image.flavor
        value: fpm
      - name: image.tag
        value: full
      - name: ingress.className
        value: nginx
      - name: ingress.enabled
        value: true
      - name: nextcloud.host
        value: nextcloud.kube.home
      - name: nextcloud.username
        value: koeff
      - name: nextcloud.password
        value: "1231fds23123"
      - name: nginx.enabled
        value: true
      - name: peristence.enabled
        value: false
      - name: peristence.storageClass
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: nextcloud.extraInitContainers[0].name
        value: install-smbclient
      - name: nextcloud.extraInitContainers[0].image
        value: nextcloud:stable-fpm-alpine
      - name: nextcloud.extraInitContainers[0].command[0]
        value: sh
      - name: nextcloud.extraInitContainers[0].command[1]
        value: "-c"
      - name: nextcloud.extraInitContainers[0].command[2]
        value: "apk add --no-cache procps samba-client"
    needs:
    - ns-metallb/metallb-main



  - name: qnap-proxy-endpoints
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/qnap-proxy-endpoints.yaml.gotmpl

  - name: qnap-proxy-service
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    needs: 
    - ns-homelab-main/qnap-proxy-endpoints
    values:
    - ../../values/common/qnap-proxy-service.yaml.gotmpl

  - name: qnap-proxy
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    needs: 
    - ns-homelab-main/qnap-proxy-service
    values:
    - ../../values/common/qnap-proxy.yaml.gotmpl

  - name: nginx-url-converter-static-site
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter-static-site.yaml.gotmpl

  - name: nginx-url-converter-overridden-http
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter-overridden-http.yaml.gotmpl



  - name: nginx-url-converter
    chart: bitnami/nginx
    version: 15.10.1
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter.yaml.gotmpl


  - name: metrics-server
    chart: metrics-server/metrics-server
    version: "3.11.0"
    installed: true
    recreatePods: true
    values:
    - ../../values/{{ .Environment.Name }}/metrics-server.yaml.gotmpl
  - name: prometheus
    chart: prometheus-community/prometheus
    version: "25.6.0"
    installed: true
    recreatePods: true
    values:
    - ../../values/{{ .Environment.Name }}/prometheus.yaml.gotmpl
  - name: grafana
    chart: grafana/grafana
    version: 7.0.8
    installed: true
    values:
    - ../../values/{{ .Environment.Name }}/grafana-dashboard.yaml
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.13.2
    installed: true
    namespace: cert-manager
    set:
    - name: prometheus.enabled
      value: false
    - name: installCRDs
      value: true
  - name: cert-manager-tokens
    chart: k0eff-home-lab-charts/helperChart
    installed: true
    namespace: cert-manager
    needs:
    - cert-manager/cert-manager
    set:
      - name: "helperchart.secret.enabled"
        value: true
      - name: "helperchart.secret.name"
        value: cert-manager-cloudflare-token-secret
      - name: "helperchart.secret.namespace"
        value: cert-manager
      - name: "helperchart.secret.data.token"
        value: "{{ requiredEnv "CERT_MANAGER_CLOUDFLARE_TOKEN" }}"
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
  - name: cert-manager-issuers
    chart: adfinis/cert-manager-issuers
    version: 0.2.5
    installed: true
    namespace: cert-manager
    needs:
    - cert-manager/cert-manager-tokens
    - cert-manager/cert-manager
    values:
    - ../../values/{{ .Environment.Name }}/cert-manager-issuers.yaml.gotmpl

  - name: es-creds
    chart: cloudnativeapp/raw
    version: 0.2.3
    installed: true
    namespace: elastic-system
    values:
    - ../../values/{{ .Environment.Name }}/es-creds.yaml.gotmpl

  - name: elasticsearch
    chart: elastic/elasticsearch
    version: 7.17.3
    installed: true
    namespace: elastic-system
    values:
    - ../../values/{{ .Environment.Name }}/elasticsearch.yaml.gotmpl

  - name: elastic-indexes-ensure
    chart: cloudnativeapp/raw
    installed: false
    namespace: elastic-system
    labels:
      reinstall: everytime
      target: indexes
    values:
    - ../../values/{{ .Environment.Name }}/elastic-indexes-ensure-job.yaml.gotmpl
    hooks:
    - events: ["prepare"]
      showlogs: true
      command: "helmfile"
      args: ["-e", "{{ .Environment.Name }}", "destroy", "-l", "reinstall=everytime", "-l", "target=indexes", "-f", "helmfile.yaml", "--skip-charts"] # ensure fresh every time

  - name: kibana
    chart: elastic/kibana
    version: 7.17.3
    installed: true
    force: true
    namespace: elastic-system
    values:
    - ../../values/{{ .Environment.Name }}/kibana.yaml.gotmpl

  - name: filebeat-fields-yaml
    chart: cloudnativeapp/raw
    installed: true
    namespace: elastic-system
    values:
    - ../../values/{{ .Environment.Name }}/filebeat-fields-yaml.yaml.gotmpl


  - name: filebeat
    chart: elastic/filebeat
    version: 7.17.3
    installed: true
    namespace: elastic-system
    values:
    - ../../values/{{ .Environment.Name }}/filebeat.yaml.gotmpl
