{{- if .Values.helperchart }}
{{- if .Values.helperchart.ipaddresspool }}
{{- if .Values.helperchart.ipaddresspool.enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.helperchart.ipaddresspool.name }}
  namespace: {{ .Values.helperchart.ipaddresspool.namespace }}
spec:
  addresses:
  {{- range .Values.helperchart.ipaddresspool.addresses }}
    - {{ . }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
