{{- if .Values.helperchart }}
{{- if .Values.helperchart.secret }}
{{- if .Values.helperchart.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.helperchart.secret.name }}
  namespace: {{ .Values.helperchart.secret.name }}
  data:
{{- range $key, $value := .Values.helperchart.secret.data }}
    {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}