commonLabels:
  env: cluter00

repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: k0eff-home-lab-charts
    url: https://github.com/k0eff/helmfile-home-lab/raw/main/helm/packages/
  - name: metallb
    url: https://metallb.github.io/metallb/
  - name: csi-driver-smb
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/

---
environments:
  cluster00:
    values:
      - ../../values/common/shared.yaml
      - ../../values/cluster00/cluster00-vals.yaml
      - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml


---
helmDefaults:
  kubeContext: kubernetes-admin@cluster00.local


releases:
  - name: storage-class-default
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: "helperchart.storageClass.annotations.storageclass\\.kubernetes\\.io/is-default-class"
        value: true
      - name: "helperchart.storageClass.parameters.fstype"
        value: xfs # https://www.phoronix.com/review/linux-58-filesystems/4
      - name: "helperchart.storageClass.parameters.storagepolicyname"
        value: {{ .Environment.Name }}Policy
      - name: "helperchart.storageClass.allowVolumeExpansion"
        value: true
      - name: "helperchart.storageClass.provisioner"
        value: "csi.vsphere.vmware.com"
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
  - name: organizr-main
    namespace: ns-homelab-main
    chart: k8s-at-home/organizr
    values:
    - ../../templates/organizr/values.yaml.gotmpl
    set:
    - name: persistence.config.size
      value: 1.05Gi
    - name: persistence.config.enabled
      value: true
    installed: true
  - name: namespace-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.namespace.enabled"
        value: true
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
    createNamespace: false
  - name: metallb-main
    namespace: {{.Values.helperchart.namespace.name}}
    chart: metallb/metallb
    installed: true
    values:
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
  - name: ipaddresspool-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.ipaddresspool.enabled"
        value: true
      - name: "helperchart.ipaddresspool.name"
        value: "internal"
      - name: "helperchart.ipaddresspool.namespace"
        value: {{.Values.helperchart.namespace.name}}
    values:
    - ../../values/{{ .Environment.Name }}/ipaddresspool-metallb.yaml
    needs: # as it uses a CRD - make sure to run the diff after installing the CRDs with the metallb release
    - ns-metallb/metallb-main
    installed: true
  - name: ingress-nginx-main
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    namespace: ns-homelab-main
    values:
    - ../../values/{{ .Environment.Name }}/ingress-nginx.yaml

  - name: nextcloud
    chart: nextcloud/nextcloud
    version: 4.2.1
    installed: false
    values:
    - ../../values/{{ .Environment.Name }}/nextcloud.yaml.gotmpl
    needs:
    - ns-metallb/metallb-main


# SMB
  - name: csi-driver-smb
    chart: csi-driver-smb/csi-driver-smb
    namespace: kube-system
    version: 1.12.0
    installed: false


# SMB1
  - name: secret-smb1
    chart: k0eff-home-lab-charts/helperChart
    namespace: ns-homelab-main
    installed: false
    set:
      - name: "helperchart.secret.enabled"
        value: true
      - name: "helperchart.secret.name"
        value: secret-smb-{{ requiredEnv "PHOTOPRISM1_SMB_SHARE_SECRET_SUFFIX" }}
      - name: "helperchart.secret.namespace"
        value: ns-homelab-main
      - name: "helperchart.secret.data.username"
        value: "{{ requiredEnv "PHOTOPRISM1_SMB_SHARE_USERNAME" }}"
      - name: "helperchart.secret.data.password"
        value: "{{ requiredEnv "PHOTOPRISM1_SMB_SHARE_PASSWORD" }}"
    values:
    - ../../templates/helperChart/values.yaml.gotmpl

  - name: storage-class-smb1
    chart: k0eff-home-lab-charts/helperChart
    installed: false
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-smb1
      - name: "helperchart.storageClass.provisioner"
        value: "smb.csi.k8s.io"
      - name: "helperchart.storageClass.parameters.source"
        value: "{{ requiredEnv "PHOTOPRISM1_SMB_SHARE_ADDRESS" }}"
      - name: "helperchart.storageClass.parameters.csi\\.storage\\.k8s\\.io/node-stage-secret-name"
        value: "secret-smb-{{ requiredEnv "PHOTOPRISM1_SMB_SHARE_SECRET_SUFFIX" }}"
      - name: "helperchart.storageClass.parameters.csi\\.storage\\.k8s\\.io/node-stage-secret-namespace"
        value: "ns-homelab-main"
      - name: "helperchart.storageClass.reclaimPolicy"
        value: Delete
      - name: "helperchart.storageClass.volumeBindingMode"
        value: Immediate
      - name: "helperchart.storageClass.mountOptions[0]"
        value: dir_mode=0555
      - name: "helperchart.storageClass.mountOptions[1]"
        value: file_mode=0555
      - name: "helperchart.storageClass.mountOptions[2]"
        value: uid=0
      - name: "helperchart.storageClass.mountOptions[3]"
        value: gid=0
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    needs:
    - ns-metallb/metallb-main


  - name: photoprism
    chart: k8s-at-home/photoprism
    installed: false
    namespace: ns-homelab-main
    version: 5.0.0
    values:
    - ../../values/{{ .Environment.Name }}/photoprism1.yaml.gotmpl
    needs:
    - kube-system/csi-driver-smb
    - ns-homelab-main/secret-smb1


# SMB 2

  - name: secret-smb2
    chart: k0eff-home-lab-charts/helperChart
    namespace: ns-homelab-main
    installed: false
    set:
      - name: "helperchart.secret.enabled"
        value: true
      - name: "helperchart.secret.name"
        value: secret-smb-{{ requiredEnv "PHOTOPRISM2_SMB_SHARE_SECRET_SUFFIX" }}
      - name: "helperchart.secret.namespace"
        value: ns-homelab-main
      - name: "helperchart.secret.data.username"
        value: "{{ requiredEnv "PHOTOPRISM2_SMB_SHARE_USERNAME" }}"
      - name: "helperchart.secret.data.password"
        value: "{{ requiredEnv "PHOTOPRISM2_SMB_SHARE_PASSWORD" }}"
    values:
    - ../../templates/helperChart/values.yaml.gotmpl

  - name: storage-class-smb2
    chart: k0eff-home-lab-charts/helperChart
    installed: false
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-smb2
      - name: "helperchart.storageClass.provisioner"
        value: "smb.csi.k8s.io"
      - name: "helperchart.storageClass.parameters.source"
        value: "{{ requiredEnv "PHOTOPRISM2_SMB_SHARE_ADDRESS" }}"
      - name: "helperchart.storageClass.parameters.csi\\.storage\\.k8s\\.io/node-stage-secret-name"
        value: "secret-smb-{{ requiredEnv "PHOTOPRISM2_SMB_SHARE_SECRET_SUFFIX" }}"
      - name: "helperchart.storageClass.parameters.csi\\.storage\\.k8s\\.io/node-stage-secret-namespace"
        value: "ns-homelab-main"
      - name: "helperchart.storageClass.reclaimPolicy"
        value: Delete
      - name: "helperchart.storageClass.volumeBindingMode"
        value: Immediate
      - name: "helperchart.storageClass.mountOptions[0]"
        value: dir_mode=0444
      - name: "helperchart.storageClass.mountOptions[1]"
        value: file_mode=0444
      - name: "helperchart.storageClass.mountOptions[2]"
        value: uid=0
      - name: "helperchart.storageClass.mountOptions[3]"
        value: gid=0
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    needs:
    - ns-metallb/metallb-main


  - name: photoprism2
    chart: k8s-at-home/photoprism
    installed: false
    namespace: ns-homelab-main
    version: 5.0.0
    values:
    - ../../values/{{ .Environment.Name }}/photoprism2.yaml.gotmpl
    needs:
    - kube-system/csi-driver-smb
    - ns-homelab-main/secret-smb2



  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.13.2
    installed: true
    namespace: cert-manager
    set:
    - name: prometheus.enabled
      value: false
    - name: installCRDs
      value: true
  - name: cert-manager-tokens
    chart: k0eff-home-lab-charts/helperChart
    installed: true
    namespace: cert-manager
    needs:
    - cert-manager/cert-manager
    set:
      - name: "helperchart.secret.enabled"
        value: true
      - name: "helperchart.secret.name"
        value: cert-manager-cloudflare-token-secret
      - name: "helperchart.secret.namespace"
        value: cert-manager
      - name: "helperchart.secret.data.token"
        value: "{{ requiredEnv "CERT_MANAGER_CLOUDFLARE_TOKEN" }}"
    values:
    - ../../templates/helperChart/values.yaml.gotmpl

  - name: cert-manager-issuers
    chart: adfinis/cert-manager-issuers
    version: 0.2.5
    installed: true
    namespace: cert-manager
    needs:
    - cert-manager/cert-manager-tokens
    - cert-manager/cert-manager
    values:
    - ../../values/{{ .Environment.Name }}/cert-manager-issuers.yaml.gotmpl




  - name: qnap-proxy-endpoints
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/qnap-proxy-endpoints.yaml.gotmpl

  - name: qnap-proxy-service
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    needs: 
    - ns-homelab-main/qnap-proxy-endpoints
    values:
    - ../../values/common/qnap-proxy-service.yaml.gotmpl

  - name: qnap-proxy
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    needs: 
    - ns-homelab-main/qnap-proxy-service
    values:
    - ../../values/common/qnap-proxy.yaml.gotmpl







  - name: nginx-url-converter-static-site
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter-static-site.yaml.gotmpl

  - name: nginx-url-converter-overridden-http
    chart: cloudnativeapp/raw
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter-overridden-http.yaml.gotmpl



  - name: nginx-url-converter
    chart: bitnami/nginx
    version: 15.10.1
    installed: true
    namespace: ns-homelab-main
    values:
    - ../../values/common/nginx-url-converter.yaml.gotmpl
