commonLabels:
  env: cluter00

repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: k0eff-home-lab-charts
    url: https://github.com/k0eff/helmfile-home-lab/raw/main/helm/packages/
  - name: metallb
    url: https://metallb.github.io/metallb/

---
environments:
  cluster00:
    values:
      - ../../values/common/shared.yaml
      - ../../values/cluster00/cluster00-vals.yaml
      - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml


---

releases:
  - name: storage-class-default
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.storageClass.enabled"
        value: true
      - name: "helperchart.storageClass.name"
        value: {{ .Environment.Name }}-storageclass-datastore1
      - name: "helperchart.storageClass.fstype"
        value: xfs # https://www.phoronix.com/review/linux-58-filesystems/4
      - name: "helperchart.storageClass.storagePolicyName"
        value: {{ .Environment.Name }}Policy
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
  - name: organizr-main
    namespace: ns-homelab-main
    chart: k8s-at-home/organizr
    values:
    - ../../templates/organizr/values.yaml.gotmpl
    installed: true
  - name: namespace-metallb
    chart: k0eff-home-lab-charts/helperChart
    set:
      - name: "helperchart.namespace.enabled"
        value: true
    values:
    - ../../templates/helperChart/values.yaml.gotmpl
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml
    createNamespace: false
  - name: metallb-main
    namespace: {{.Values.helperchart.namespace.name}}
    chart: metallb/metallb
    installed: true
    values:
    - ../../values/{{ .Environment.Name }}/namespace-metallb.yaml

helmDefaults:
  kubeContext: kubernetes-admin@cluster00.local
